### ISSUE TITLE
Getting Invalid string length error

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/steel-flint#18]
Not sure how to reproduce, but I've gotten in twice now in the past few hours. This is when live coding is off:

Edit: **It won't stop...was constant. Had to disable package**

``` javascript
RangeError: Invalid string length
    at Object.stringify (native)
    at /Users/Developer/.atom/packages/linter/lib/validate.coffee:53:25
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (/Users/Developer/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (/Users/Developer/.atom/packages/linter/lib/message-registry.js:36:16)
    at /Users/Developer/.atom/packages/linter/lib/linter.coffee:35:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/Developer/.atom/packages/linter/lib/indie-registry.js:27:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Indie.setMessages (/Users/Developer/.atom/packages/linter/lib/indie.js:15:18)
    at /Users/Developer/.atom/packages/steel-flint/lib/main.js:99:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Linter.updateMessages (/Users/Developer/.atom/packages/steel-flint/lib/linter.js:36:18)
    at Linter.setError (/Users/Developer/.atom/packages/steel-flint/lib/linter.js:25:10)
    at /Users/Developer/.atom/packages/steel-flint/lib/main.js:93:19
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at HTMLDivElement.<anonymous> (/Users/Developer/.atom/packages/steel-flint/lib/connection.js:19:20)
    at WebSocket.ws.onmessage (/Users/Developer/.atom/packages/steel-flint/node_modules/reconnectingwebsocket/reconnecting-websocket.js:278:29)
```

**Comment by ncammarata** [comment]
woah how did you find steel flint?

**Comment by ncammarata** [comment]
also I've run into this too and disabled linter. Pretty high priority @steelbrain

**Comment by AriaFallah** [comment]
@ncammarata lol my github profile picture is the same as my slack one...

Steel posted about it there, and after asking nate I thought I'd test it out.

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
@ncammarata This is actually a bug in the flint compiler. This package was assuming it would send good messages each time but now it can handle invalid ones too. If you come across an invalid message again, please check your console and post the debug info you see there

**Comment by steelbrain** [comment]
After some discussion with @natew we found out that the flint server could be sending all kinds of error messages including those from webpack and gulp through the same error event as build error. It's what causing this error & confusion, Nate says he's gonna add a new `build:error` type which will only have build errors.

After he has done it I'll migrate this package to use that event for build message and will show a warning notification for each other error so the user knows they have happened
